### ISSUE TITLE
pretrain the basenet

### ISSUE THREAD

**Issue by JongMokKim** [scaelles/DEXTR-PyTorch#12]
Hi, thank you for nice work!

I have a question about pretraining the basenet on imagenet

your base network has 4 channel input (h x w x 4(rgb-guassian)),
but it should be 3 channels when pretraining the imagenet (imagenet data only has rgb and extreme points is not necessary to classify task)

how did you do it? 
thank you for your help in advance!

**Comment by kmaninis** [comment]
Hi, thanks for your kind words.

The network was indeed pre-trained on Imagenet using 3 channels.
We artificially added a fourth channel to train DEXTR, and initialized its weights from Imagenet.
Please take a look at [this part](https://github.com/scaelles/DEXTR-PyTorch/blob/67ca085f9509eeb2b168b07294d72f7625509fa5/networks/deeplab_resnet.py#L206) of the code.

**Comment by JongMokKim** [comment]
thank you very much!
