### ISSUE TITLE
helpers.py leads to an error

### ISSUE THREAD

**Issue by shirishr** [scaelles/DEXTR-PyTorch#13]
I am on python 3
Line 159:

if inds[0].shape[0] == 0:

leads to error

IndexError: index 0 is out of bounds for axis 0 with size 0

inds[0] is a one dimensional array with 4 integers type np.Int64. So inds[0].shape[0] trows out error

**Comment by scaelles** [comment]
Hello,
Those inds are obtained from the clicks on the demo image that are captured [here](https://github.com/scaelles/DEXTR-PyTorch/blob/67ca085f9509eeb2b168b07294d72f7625509fa5/demo.py#L48). It should be a tuple of np.ndarray like array([[327, 267, 215, 266], [319, 376, 319, 272]]). That error seems to appear sometimes when you close the window of the image that is shown. 

Our method works with four user input click, the left most, bottom most, right most and top most pixels of the object. I would encourage you to do those 4 clicks and then the result should appear in the same window (don't close it!).

**Comment by shirishr** [comment]
@scaelles,
Thanks Sergi,
I think it works the way you intended it.
I think the error occurs when you hit enter key. The image window closes but the code does not gracefully exit from the loop.
Minor stuff...I was thrown off when I saw it on the console.
Very minor and hence closing it.
Thank you

**Comment by shirishr** [comment]
@scaelles
Sergi,

It would be nice if one could export a mask png image

or

export a json file

:100:

**Comment by NicksonYap** [comment]
I'm facing the same exact same with the latest commit 00a0a84002992df506c9fda6a685bd496a67f097

However I'm using PyTorch 1.0

The masking works well with the dog and cat, however upon pressing enter, the same error appears:

> I am on python 3
> Line 159:
> 
> if inds[0].shape[0] == 0:
> 
> leads to error
> 
> IndexError: index 0 is out of bounds for axis 0 with size 0
> 
> inds[0] is a one dimensional array with 4 integers type np.Int64. So inds[0].shape[0] trows out error

**Comment by scaelles** [comment]
Hello,

The error does not affect the final result, but I have updated the code to handle such situation.
Also, I have tested the code in master with Pytorch 1.0.1 and it should work.
Now, it also saves the mask of the annotated objects in an indexed PNG.

Let me know if you have any further questions.

**Comment by NicksonYap** [comment]
Yup, tested to be working again on my end :)
