### ISSUE TITLE
Cannot reproduce the same result as provided Dextr_pascal-sbd model

### ISSUE THREAD

**Issue by Valentine233** [scaelles/DEXTR-PyTorch#14]
Thanks for your great work!

When I reproduce your results of Dextr_pascal-sbd, I cannot get the same performance (IoU=91.5).

Firstly, I just evaluate with your provided model "dextr_pascal-sbd.pth" and I can get the IoU of 91.5. However, when I try to train the model by myself, I only get the IoU of 86.2, with a gap of 5.3. I have barely changed your codes.

Here is my setup:
- python 3.6.6
- pytorch 0.4.0
- gpu Titan X

Could you please give me some suggestions :)

**Comment by kmaninis** [comment]
Hi, could you try with different thresholds during evaluation? We have checked reproducibility at least 3 times, for different versions of PyTorch. Also, default behaviour of upsampling has changed (aligned corners), which should be fine if you stick to the given code.

**Comment by Valentine233** [comment]
Thanks for your suggestion.

Changing thresholds is helpful!

**Comment by kmaninis** [comment]
Hi, let us know whether this was the only problem.
