### ISSUE TITLE
Model conversion 

### ISSUE THREAD

**Issue by bsekachev** [scaelles/DEXTR-PyTorch#16]
As far as I understand you have converted PyTorch weights to Keras weighs. Right?
How have you done it? Have you used an intermediate ONNX format?

**Comment by scaelles** [comment]
Hello,
I didn't use ONNX, I manually saved all the weights into numpy and then load them from numpy in Keras. You can find the script that I used [here](https://gist.github.com/scaelles/4c75d17e8f04324547faa10fa3cba661) and then the function to load from numpy [here](https://github.com/scaelles/DEXTR-KerasTensorflow/blob/d29d4c1ad48fc9d1d735d48aa27b494ac006ef11/networks/dextr.py#L45)

Let me know if you have any further question.

**Comment by bsekachev** [comment]
Hello,
Thank you so much.

**Comment by bhavesh907** [comment]
Hi, @scaelles how did you convert your PyTorch model in .bin and .xml format for cvat tool? .
