### ISSUE TITLE
UR CODE WAS COPIED FOR SELL NOW 

### ISSUE THREAD

**Issue by genema** [scaelles/DEXTR-PyTorch#19]
http://manaai.cn/aicodes_detail3.html?id=31
A group of contemptible thieves has clone ur code, replace ur license with theirs and peddling 
it on their "WEBSITE".

**Comment by xmaj2008** [comment]
and this site too.
http://codes.strangeai.pro/aicodes_detail.html?id=31

**Comment by kmaninis** [comment]
Hi, thanks to both for reporting this disappointing event!
