### ISSUE TITLE
Training time of PASCAL VOC 2012

### ISSUE THREAD

**Issue by michaelzhou0723** [scaelles/DEXTR-PyTorch#22]
Hello! I run the provided train_pascal.py (PSCAL VOC  2012 without SBD) on a Tesla V100 GPU, and it seems to take roughly half an hour to complete one epoch. But in the publication you mentioned it took you 20 hours for 100 epochs on a Titan X. Is there anything I should tune in order to achieve the same speed?

**Comment by scaelles** [comment]
Hello,
Training time depends on a lot of factors and the GPU is only one of them. I would recommend that you maximize the GPU utilization making sure that reading the data is not the bottleneck.
