### ISSUE TITLE
I can't click the extreme points in the picture

### ISSUE THREAD

**Issue by Hhy1024** [scaelles/DEXTR-PyTorch#24]
Hi,
   when I run demo.py,it shows 
![demo](https://user-images.githubusercontent.com/43701309/67833731-76131c80-fb20-11e9-83c7-66c8b575bdb5.jpg),but I can't click the extreme points in the picture as you shown in gif,What else do I need to do?

**Comment by Luoxd1996** [comment]
Hi,
MIDeepSeg (https://github.com/Luoxd1996/MIDeepSeg) is a solution for
interactive medical image segmentation extends from DEXTR, but the provided
2D-GUIs may use to replace the demo of Deep Extreme Cut.
Best.

Mahnoor-Solangi ***@***.***> 于2021年8月27日周五 上午7:10写道：
