### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by Hhy1024** [scaelles/DEXTR-PyTorch#25]
when I run demo.py,it shows
![demo](https://user-images.githubusercontent.com/43701309/67838419-34886e80-fb2c-11e9-8824-72129277e9eb.jpg),what's  wrong with the code?

**Comment by scaelles** [comment]
Hello,

Another user reported a similar problem and in his/her case changing to Python 3.6 fixed the issue: https://github.com/scaelles/DEXTR-KerasTensorflow/issues/1

Let us know if that helps!

**Comment by Hhy1024** [comment]
> Hello,
> 
> Another user reported a similar problem and in his/her case changing to Python 3.6 fixed the issue: [scaelles/DEXTR-KerasTensorflow#1](https://github.com/scaelles/DEXTR-KerasTensorflow/issues/1)
> 
> Let us know if that helps!

Thx for your reply!But my python version is 
![python](https://user-images.githubusercontent.com/43701309/67926855-1b49f580-fbf2-11e9-91d8-39951ad333e4.jpg),it still gets the same error

**Comment by kmaninis** [comment]
Hi, did you use the pytorch version that is recommended?
