### ISSUE TITLE
Results on background classes of PASCAL Context 

### ISSUE THREAD

**Issue by Dingry** [scaelles/DEXTR-PyTorch#28]
Hi, I cannot reproduce the result of 81.75 mIoU reported in your paper, after training according to the parameters you provided and adjusting the threshold.
Can you provide the trained model or give me some advice on the hyper-parameters adjustments?

**Comment by kmaninis** [comment]
Hi, we are not planning to release more on this project, but we would be happy to help. Could you give us more information? Did you try on the subset of the classes, same as in our experiments? The hyper-parameters were not modified.
