### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by skycode1** [scaelles/DEXTR-PyTorch#29]
Hi,
Getting error while running demo.py plz help...
![issue](https://user-images.githubusercontent.com/63158841/82747486-d0264880-9db6-11ea-9b2d-dca4036cc4e6.PNG)

**Comment by scaelles** [comment]
Hello,
Unfortunately, we have not tried our codebase in Windows and therefore we do not support it.
