### ISSUE TITLE
Can't reproduce results running demo.py 

### ISSUE THREAD

**Issue by howard-mahe** [scaelles/DEXTR-PyTorch#3]
Hi,

Thank you for this work!
I am using PyTorch, Python 2.7, Ubuntu 14.04 ~~Keras, TF 1.4~ implementation of DEXTR. I haven't succeed to reproduce the results you show in the GIF.

Here's what I got running the demo:
- Pascal
![dextr_pascal](https://user-images.githubusercontent.com/17425914/38514285-1502be00-3c31-11e8-9dea-1fafebccff81.png)
- Pascal+SBD
![dextr_pascal-sdb](https://user-images.githubusercontent.com/17425914/38514288-18f111a6-3c31-11e8-8204-4f6f9fb805bd.png)
- COCO
![dextr_coco](https://user-images.githubusercontent.com/17425914/38514378-51f47628-3c31-11e8-89ab-719d768d565c.png)

Any idea?

**Comment by scaelles** [comment]
Hello,
Thanks for your comments!
We tested our code using Python 3.6 and not Python 2.7 so it would be better if you could test with the newer Python version.
Also, you describe that you have Keras and TF, but for the implementation in this repo you need Pytorch. The Keras with TF backend version is [here](https://github.com/scaelles/DEXTR-KerasTensorflow).
Let us know if you have any other questions!

**Comment by howard-mahe** [comment]
Hello,

Thanks for your feedback. 

My mistake about Keras, I tried both project but here is the results with PyTorch. I edited my first post.

I'll try tomorrow with Python 3.6 and I'll let you know.

**Comment by howard-mahe** [comment]
Hi,
I failed to build a working virtualenv with Python3.6 on Ubuntu14.04, so I'll stop playing with DEXTR for now. Thanks for your time.

**Comment by scaelles** [comment]
I am sorry to hear that. I would recommend you installing Miniconda as suggested in the Readme instead of the virtualenv if you want to give it a last shot.

**Comment by howard-mahe** [comment]
I can't either have a working Miniconda (2 and 3) since I had issue with conda calling `from pip._vendor.requests`
I'll probably try on a cleaner installation of Ubuntu 14.04, later.

Thank you.

**Comment by ashutoshraj** [comment]
after annotating with four points, complete image is becoming black.
