### ISSUE TITLE
Speed metrics ?

### ISSUE THREAD

**Issue by Ownmarc** [scaelles/DEXTR-PyTorch#30]
Hello,

Do you have any speed metrics ? Something like images per seconds stating image size + GPU type ?

Thanks and nice work! Looking to port this to TFJS to be used in an annotation project for semi auto segmentation.

**Comment by kmaninis** [comment]
Hi, in our experiments image size was always 512 x 512 and it took roughly 80ms per image for the forward pass (on a Titan-X GPU). Or are you also counting the time to click on the extreme points? If so, passing the image through the CNN is negligible. Please take a look at Section 4.1 "Training and testing details".

**Comment by Ownmarc** [comment]
That was the metric I was after, thanks!
