### ISSUE TITLE
Performance of DEXTR with 2 or 3 points

### ISSUE THREAD

**Issue by SebastienLinker** [scaelles/DEXTR-PyTorch#32]
Hi,

DEXTR is an amazing tool. Out of curiosity, have you tried training DEXTR with only 2 or 3 extreme points?
I am interested in using this tool to segment long and thin objects like tree trunks, springs, road lanes ...

Thanks

**Comment by kmaninis** [comment]
Hello, thanks for the kind words. With 2 or 3 extreme points we are not able to recover the bounding box (in most cases). The bounding box leads to substantial performance improvements (Table 2, first row in the paper).

**Comment by scaelles** [comment]
As @kmaninis mentioned it is quite important for our method to use a bounding boxes. If you think you can obtain one from the 2 or 3 extreme points by assuming some parameters ie clicking the top and bottom and assuming always a fix width, then you could give it try!

**Comment by SebastienLinker** [comment]
Thanks

It actually works on those long and thin objects, where 2 extreme points are physically close to each others
