### ISSUE TITLE
List out of range

### ISSUE THREAD

**Issue by ahmadalideeb** [scaelles/DEXTR-PyTorch#37]
Hello, thanks for your work)

https://github.com/scaelles/DEXTR-PyTorch/blob/352ccc76067156ebcf7267b07e0a5e43d32e83d5/dataloaders/custom_transforms.py#L34

It should be rot = self.rots[random.randint(0, len(self.rots)-1)]
and the same issue for scales on the next line

**Comment by kmaninis** [comment]
Hi, this should work as is, since it is the numpy variant:
https://github.com/scaelles/DEXTR-PyTorch/blob/352ccc76067156ebcf7267b07e0a5e43d32e83d5/dataloaders/custom_transforms.py#L3

See here:
https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

**Comment by ahmadalideeb** [comment]
Thanks))
