### ISSUE TITLE
I have a some question about pascal voc train

### ISSUE THREAD

**Issue by dypark86** [scaelles/DEXTR-PyTorch#8]
Thanks for your jobs!

I have a some question about train method
I train pascal voc dataset model with basic setting.
and evaluate model with eval_all.py.

but there are some gap in the performance.
 - my model 87.2
 - your model 90.5
 - 3.3 gap

there are some more training technic?
 - i train just 100 epoch.
 - more train epoch needs?

thanks!

**Comment by kmaninis** [comment]
Hi,

Could you provide some more info about the setup you are using? Python/PyTorch version, GPU, etc.?
The number should be reproducible just by running the script, without changing any parameters (tripple checked).

**Comment by dypark86** [comment]
i tried with following setup
 - pytorch version 0.4.0
 - 1 gpu, Titan V
 - 5 batches

after setting the data path 
i edit just following code
 -> before: device = torch.device("cuda:"+str(gpu_id) if torch.cuda.is_available() else "cpu")
 -> after: device = torch.device("cuda")
     because setgpuid make error in my env

and i train with train_pascal.py
and eval with eval_all.py

Thanks!

**Comment by scaelles** [comment]
Hello,
We tried with the same configuration except that we are using a TItan Xp, but it shouldn't make a difference. Could you try to modify the threshold in [`eval_all.py`](https://github.com/scaelles/DEXTR-PyTorch/blob/67ca085f9509eeb2b168b07294d72f7625509fa5/eval_all.py#L31)?
Best,
Sergi
